-- Rollback 002: Drop all FHIR-aligned tables created in 002
DROP TABLE IF EXISTS immunization CASCADE;
DROP TABLE IF EXISTS diagnosis CASCADE;
DROP TABLE IF EXISTS medication CASCADE;
DROP TABLE IF EXISTS allergy CASCADE;
DROP TABLE IF EXISTS observation CASCADE;
DROP TABLE IF EXISTS encounter CASCADE;
DROP TABLE IF EXISTS contact_point CASCADE;
DROP TABLE IF EXISTS patient_identifier CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
